//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace EomGetPatientAppointments {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.e-mis.com/emisopen/MedicalRecord")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.e-mis.com/emisopen/MedicalRecord", IsNullable=false)]
    public partial class PatientAppointmentList {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Appointment")]
        public AppointmentStruct[] Appointment;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.e-mis.com/emisopen/MedicalRecord")]
    public partial class AppointmentStruct {
        
        /// <remarks/>
        public int SlotID;
        
        /// <remarks/>
        public int SiteID;
        
        /// <remarks/>
        public string Date;
        
        /// <remarks/>
        public string StartTime;
        
        /// <remarks/>
        public string Duration;
        
        /// <remarks/>
        public string Notes;
        
        /// <remarks/>
        public string Reason;
        
        /// <remarks/>
        public string SessionName;
        
        /// <remarks/>
        public int SessionDBID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Holder", IsNullable=false)]
        public HolderStruct[] HolderList;
        
        /// <remarks/>
        public string Status;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.e-mis.com/emisopen/MedicalRecord")]
    public partial class HolderStruct {
        
        /// <remarks/>
        public int DBID;
        
        /// <remarks/>
        public int RefID;
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string FirstNames;
        
        /// <remarks/>
        public string LastName;
    }
}
